# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b5a5bbfcbbb32486c95500e09a26b7d777614f319b6f9b0406aa74524dc53c094030819ad6095df5ad5bce62034a8395e45cbe09ee165fa47d087e0f98b9a5f

test:
  secret_key_base: 05ae110846d53ae8903430c52ac76ed8a8ca50b2d8181731b718f7fed08c7391505b3c575356448a523372baa4d3a83d6aea39404865852216d32eae685a8920

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
